#!/usr/bin/env python3
"""Generate per-slide SVG task files and optional SVG stubs from notes/slides.md."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import List, Tuple

SVG_TEMPLATE = """<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"{viewbox}\" width=\"100%\" height=\"100%\">\n  <rect width=\"100%\" height=\"100%\" fill=\"#FFFFFF\"/>\n  <text x=\"64\" y=\"96\" font-size=\"32\" font-family=\"Arial, PingFang SC, Microsoft YaHei, sans-serif\" fill=\"#111111\">{title}</text>\n  <text x=\"64\" y=\"148\" font-size=\"18\" font-family=\"Arial, PingFang SC, Microsoft YaHei, sans-serif\" fill=\"#666666\">SVG stub generated by WorkBuddy ppt-master wrapper</text>\n  <text x=\"64\" y=\"200\" font-size=\"16\" font-family=\"Arial, PingFang SC, Microsoft YaHei, sans-serif\" fill=\"#444444\">Replace this stub with real slide artwork based on the paired task file.</text>\n</svg>\n"""

VIEWBOXES = {
    "ppt169": "0 0 1280 720",
    "ppt43": "0 0 1024 768",
    "xhs": "0 0 1242 1660",
    "square": "0 0 1080 1080",
    "story": "0 0 1080 1920",
    "wechat-cover": "0 0 900 383",
    "a4": "0 0 1240 1754",
}


def resolve_path(value: str) -> Path:
    return Path(value).expanduser().resolve()


def load_text(path: Path) -> str:
    if not path.exists():
        raise SystemExit(f"文件不存在: {path}")
    return path.read_text(encoding="utf-8")


def detect_format(project_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    design_spec = project_path / "design_spec.md"
    if design_spec.exists():
        match = re.search(r"-\s*Format:\s*([A-Za-z0-9\-]+)", design_spec.read_text(encoding="utf-8"))
        if match:
            return match.group(1)
    return "ppt169"


def parse_slide_sections(content: str) -> List[Tuple[int, str, str]]:
    pattern = re.compile(r"^##\s+Slide\s+(\d+)[^\n]*\n", re.MULTILINE)
    matches = list(pattern.finditer(content))
    if not matches:
        raise SystemExit("未在 slides.md 中找到任何 '## Slide XX' 标题。")

    sections: List[Tuple[int, str, str]] = []
    for index, match in enumerate(matches):
        slide_no = int(match.group(1))
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        body = content[start:end].strip()
        title = extract_title(body) or f"Slide {slide_no:02d}"
        sections.append((slide_no, title, body))
    return sections


def extract_title(body: str) -> str | None:
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("- 页面标题："):
            return stripped.replace("- 页面标题：", "", 1).strip() or None
        if stripped.startswith("- Title:"):
            return stripped.replace("- Title:", "", 1).strip() or None
    return None


def extract_field(body: str, labels: List[str]) -> str:
    for line in body.splitlines():
        stripped = line.strip()
        for label in labels:
            prefix = f"- {label}："
            if stripped.startswith(prefix):
                value = stripped.replace(prefix, "", 1).strip()
                if value:
                    return value
            prefix_en = f"- {label}:"
            if stripped.startswith(prefix_en):
                value = stripped.replace(prefix_en, "", 1).strip()
                if value:
                    return value
    return "待补充"


def build_task_markdown(slide_no: int, title: str, body: str, svg_path: Path, viewbox: str) -> str:
    objective = extract_field(body, ["页面目标", "Goal"])
    message = extract_field(body, ["核心信息", "Core Message"])
    support = extract_field(body, ["支撑数据 / 案例", "Support", "Evidence"])
    layout = extract_field(body, ["建议版式", "Layout"])
    visual = extract_field(body, ["视觉提示占位", "Visual Cue", "Visual Prompt"])
    notes = extract_field(body, ["备注占位", "Speaker Notes", "Notes"])

    return f"# Slide {slide_no:02d} SVG Task\n\n## Metadata\n- Slide No: {slide_no:02d}\n- Title: {title}\n- Target SVG: {svg_path}\n- ViewBox: {viewbox}\n\n## Objective\n{objective}\n\n## Core Message\n{message}\n\n## Supporting Material\n{support}\n\n## Layout Guidance\n{layout}\n\n## Visual Guidance\n{visual}\n\n## Speaker Notes Seed\n{notes}\n\n## Source Slide Plan\n{body.strip() or '待补充'}\n"


def write_if_needed(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        print(f"跳过已存在文件: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"已写入: {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SVG task files from notes/slides.md")
    parser.add_argument("--project-path", required=True, help="项目目录")
    parser.add_argument("--slides", help="自定义 slides.md 路径")
    parser.add_argument("--tasks-dir", help="任务输出目录，默认 <project>/tasks")
    parser.add_argument("--manifest", help="manifest 输出路径，默认 <project>/svg_output_manifest.json")
    parser.add_argument("--format", help="显式指定画布格式，例如 ppt169 / xhs")
    parser.add_argument("--viewbox", help="显式指定 viewBox，优先级高于 format")
    parser.add_argument("--create-svg-stubs", action="store_true", help="同时为每页生成 svg_output/*.svg 占位文件")
    parser.add_argument("--force", action="store_true", help="覆盖已有任务文件和 stub")
    args = parser.parse_args()

    project_path = resolve_path(args.project_path)
    slides_path = resolve_path(args.slides) if args.slides else project_path / "notes" / "slides.md"
    tasks_dir = resolve_path(args.tasks_dir) if args.tasks_dir else project_path / "tasks"
    manifest_path = resolve_path(args.manifest) if args.manifest else project_path / "svg_output_manifest.json"
    svg_dir = project_path / "svg_output"

    content = load_text(slides_path)
    fmt = detect_format(project_path, args.format)
    viewbox = args.viewbox or VIEWBOXES.get(fmt, "0 0 1280 720")
    sections = parse_slide_sections(content)

    manifest = {
        "project_path": str(project_path),
        "format": fmt,
        "viewbox": viewbox,
        "slides": [],
    }

    for slide_no, title, body in sections:
        task_path = tasks_dir / f"slide-{slide_no:02d}.md"
        svg_path = svg_dir / f"slide-{slide_no:02d}.svg"
        task_content = build_task_markdown(slide_no, title, body, svg_path, viewbox)
        write_if_needed(task_path, task_content, args.force)

        if args.create_svg_stubs:
            svg_content = SVG_TEMPLATE.format(viewbox=viewbox, title=title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
            write_if_needed(svg_path, svg_content, args.force)

        manifest["slides"].append(
            {
                "slide_no": slide_no,
                "title": title,
                "task_file": str(task_path),
                "svg_stub": str(svg_path),
            }
        )

    write_if_needed(manifest_path, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", True)
    print(f"已生成 {len(sections)} 份 SVG 任务文件。")


if __name__ == "__main__":
    main()
